# Generated by Django 3.1 on 2020-09-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='external_url',
            field=models.URLField(default='#'),
        ),
    ]
