# Generated by Django 3.1 on 2020-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techskills',
            options={'ordering': ['skill_index']},
        ),
        migrations.AddField(
            model_name='techskills',
            name='skill_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='techskills',
            name='skill_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
