# Generated by Django 3.1.5 on 2021-01-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='start_year',
            field=models.CharField(default=2021, max_length=4),
        ),
        migrations.AlterField(
            model_name='pe',
            name='start_year',
            field=models.CharField(default=2021, max_length=4),
        ),
    ]
