# Generated by Django 3.1 on 2020-08-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200826_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techskills',
            options={'ordering': ['index']},
        ),
        migrations.RenameField(
            model_name='techskills',
            old_name='skill_index',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='techskills',
            old_name='skill_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='techskills',
            old_name='skill_name',
            new_name='name',
        ),
    ]
