# Generated by Django 3.1.5 on 2021-01-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210128_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='pe',
            name='company',
            field=models.CharField(max_length=40),
        ),
    ]
