# Generated by Django 3.1 on 2020-08-26 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200826_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techskills',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
