# Generated by Django 3.1.5 on 2021-01-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20210129_0041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Headers',
            new_name='Header',
        ),
        migrations.RenameModel(
            old_name='ProgrammingLanguages',
            new_name='ProgrammingLanguage',
        ),
        migrations.RenameModel(
            old_name='TechSkills',
            new_name='TechSkill',
        ),
    ]
