# Generated by Django 3.1.5 on 2021-01-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20210129_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='header',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
