# Generated by Django 3.1.5 on 2021-02-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20210130_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pe',
            name='additional_time_info',
        ),
    ]
